# Generated by Django 6.0.5 on 2026-05-24 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dia',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida')], default='programada', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='consultorio.paciente'),
        ),
    ]
