# Generated by Django 6.0.5 on 2026-05-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'programada')), fields=('fecha', 'hora'), name='unique_cita_programada_por_fecha_hora'),
        ),
    ]
